fix: regression where _deep_merge() mutates list values in passed dictionary (#2400)
* no-op change to uv.lock at uv's insistence

On a fresh clone I got this error:

```
% tox run -e dev
dev: uv-sync> uv sync --locked --python-preference system --extra all --no-default-groups --group dev -p /Users/cosmo.grant/.local/share/uv/tools/tox/bin/python
Resolved 133 packages in 5.04s
error: The lockfile at `uv.lock` needs to be updated, but `--locked` was provided. To update the lockfile, run `uv lock`.
dev: exit 2 (5.11 seconds) /Users/cosmo.grant/git/personal/datamodel-code-generator> uv sync --locked --python-preference system --extra all --no-default-groups --group dev -p /Users/cosmo.grant/.local/share/uv/tools/tox/bin/python pid=46498
  dev: FAIL code 2 (5.13 seconds)
  evaluation failed :( (5.53 seconds)
```

So I ran `uv lock` as the error message suggests.

* fix regression where list is mutated unintentionally

* test jsonschema with required and anyOf required

---------

Co-authored-by: Cosmo Grant <cosmo.grant@postcodelottery.co.uk>
Co-authored-by: Koudai Aono <koxudaxi@gmail.com>